### ISSUE TITLE
EX 01 - MODULO 01 - Dúvida funcionamento das classes

### ISSUE THREAD

**Issue by GugaDavi** [Rocketseat/starter-javascript-es6-exercicios#1]
Opa Diego,

Suave?

Brow, Queria tirar uma dúvida contigo sobre o Exercio 1 do Modulo 1. Não consegui compreender corretamente o que você passou no documento do exercício com a resolução dele. Até a parte que a classe usuarios recebe email e senha, até ai suave.

Contudo, não ficou claro para mim "A classe "Admin" por sua vez não recebe parâmetros mas deve repassar os parâmetros de e-mail e senha à classe pai". Como assim? Pelo que entendi do documento da resolução você passa como parâmetro para o constructor o e-mail e senha, puxa da classe usuários os e-mails e senhas cadastrados, mas em que momento "repassamos os parâmetros para a classe pai"?

Se puder responder, vlw mesmo!

Abraços

@diego3g

**Comment by GugaDavi** [comment]
Opa Diego,

Cara infelizmente ainda não entendi, na verdade o que você explicou eu tinha sacado. Minha dúvida é quando é feito o envio dos dados cadastrados com o classe admin para a classe usuários?

**Comment by GugaDavi** [comment]
Opa Diego,

Cara infelizmente ainda não entendi, na verdade o que você explicou eu tinha sacado. Minha dúvida é quando é feito o envio dos dados cadastrados com o classe admin para a classe usuários?

@diego3g

**Comment by diego3g** [comment]
@GugaDavi No método `constructor` da classe admin que extende a classe Usuario, nós chamamos o `super(email, senha);`. Esse trecho de código vai chamar o método `constructor` da classe pai que nesse caso é Usuário repassando essas informações.

**Comment by GugaDavi** [comment]
@diego3g Então deixa ver se entendi. Quando chamamos o metodo super(), chamamos o constructor da classe pai e a partir dai o que for feito dali em diante será acrescentado nas duas classes. Correto?

**Comment by diego3g** [comment]
@GugaDavi Exato.

**Comment by GugaDavi** [comment]
Powww cara!!! Vlw pelo esclarecimento. É que sabe como é né? Cabeça dura tem que bater um pouco mais para entender... kkkkk Vlw irmão!

@diego3g
