### ISSUE TITLE
nao entendo a comparacao.

### ISSUE THREAD

**Issue by fontez** [Rocketseat/starter-javascript-es6-exercicios#3]
que faz exatamente nesta linha?
compara admin com true?
admin que valor tem? false por defeito? e essa comparacao porquê?

https://github.com/Rocketseat/starter-javascript-es6-exercicios/blob/d3b227d15b32eedf33d17232a5b8276bee6f99ae/M%C3%B3dulo%2001/01.js#L8

**Comment by diego3g** [comment]
Apenas usuários que estendem a classe de Admin possuem a propriedade `admin` como `true`, ou seja, usuários não administradores irão retornar `false` dessa condição.
